/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EMİR
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matrisIslemleri = new javax.swing.JPanel();
        matrisIslemleri.setVisible(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        olusturulanMatris = new javax.swing.JPanel();
        olusturulanMatris.setVisible(false);
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        kullanıcıMatrisi = new javax.swing.JPanel();
        kullanıcıMatrisi.setVisible(false);
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        anaPanel = new javax.swing.JPanel();
        anaPanel.setVisible(true);
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablo);

        jButton7.setText("ANA MATRİS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton11.setText("SONUÇ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BURADA YAPILAN İŞLEM YAZIYOR");

        jButton8.setText("1. İŞLEM");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("2. İŞLEM");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("GERİ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton12.setText("3. İŞLEM");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("YAPILAN TOPLAM TOPLAMA SAYISI");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("YAPILAN TOPLAM ÇARPMA SAYISI");

        javax.swing.GroupLayout matrisIslemleriLayout = new javax.swing.GroupLayout(matrisIslemleri);
        matrisIslemleri.setLayout(matrisIslemleriLayout);
        matrisIslemleriLayout.setHorizontalGroup(
            matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matrisIslemleriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matrisIslemleriLayout.createSequentialGroup()
                        .addGroup(matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(237, 237, 237)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matrisIslemleriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matrisIslemleriLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, matrisIslemleriLayout.createSequentialGroup()
                                .addGroup(matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
                                .addGap(79, 79, 79))))))
        );
        matrisIslemleriLayout.setVerticalGroup(
            matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(matrisIslemleriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(matrisIslemleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(matrisIslemleriLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(45, 45, 45)
                        .addComponent(jButton8)
                        .addGap(43, 43, 43)
                        .addComponent(jButton9)
                        .addGap(43, 43, 43)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );

        jLabel5.setText("OLUŞAN MATRİSİ");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("DEĞER GİRİNİZ");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });

        jLabel6.setText("N. SATIR N. SUTUNU GİRİNİZ");

        jButton6.setText("EKLE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout olusturulanMatrisLayout = new javax.swing.GroupLayout(olusturulanMatris);
        olusturulanMatris.setLayout(olusturulanMatrisLayout);
        olusturulanMatrisLayout.setHorizontalGroup(
            olusturulanMatrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(olusturulanMatrisLayout.createSequentialGroup()
                .addGroup(olusturulanMatrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(olusturulanMatrisLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel5))
                    .addGroup(olusturulanMatrisLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addGroup(olusturulanMatrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        olusturulanMatrisLayout.setVerticalGroup(
            olusturulanMatrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(olusturulanMatrisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jButton4.setText("GERİ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("KULLANICI TARAFINDAN GİRİLEN MATRİS PANELİ");

        jLabel3.setText("SATIR SAYISINI GİRİNZ");

        jTextField1.setText("DEĞER GİRİNİZ");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jLabel4.setText("SÜTÜN SAYISINI GİRİNİZ");

        jTextField2.setText("DEĞER GİRİNİZ");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jButton5.setText("OLUŞTUR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kullanıcıMatrisiLayout = new javax.swing.GroupLayout(kullanıcıMatrisi);
        kullanıcıMatrisi.setLayout(kullanıcıMatrisiLayout);
        kullanıcıMatrisiLayout.setHorizontalGroup(
            kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanıcıMatrisiLayout.createSequentialGroup()
                .addGroup(kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kullanıcıMatrisiLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel2))
                    .addGroup(kullanıcıMatrisiLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kullanıcıMatrisiLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(kullanıcıMatrisiLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton4)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        kullanıcıMatrisiLayout.setVerticalGroup(
            kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullanıcıMatrisiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addGroup(kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kullanıcıMatrisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );

        jButton1.setText("RASTGELE MATRİS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANA PANEL");

        jButton2.setText("KULLANICI TARAFINDAN GİRİLEN MATRİS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout anaPanelLayout = new javax.swing.GroupLayout(anaPanel);
        anaPanel.setLayout(anaPanelLayout);
        anaPanelLayout.setHorizontalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anaPanelLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addGroup(anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(314, 314, 314))
        );
        anaPanelLayout.setVerticalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(133, 133, 133)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kullanıcıMatrisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(olusturulanMatris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(matrisIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kullanıcıMatrisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(olusturulanMatris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(matrisIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
        
        anaPanel.setVisible(false);
        kullanıcıMatrisi.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Random rand = new Random();
        do{
         m = rand.nextInt(4)+1;
         n = rand.nextInt(4)+1;
        }while(m == n);
        
         matris= new float[m][n];
         for (int i = 0; i < m; i++) {
             for (int j = 0; j < n; j++) {
                        matris[i][j]= rand.nextInt(9)+1;
             }
        }
         
         String []baslik = new String[n];
            String sutSayisi;
            
            
            for(int i=0; i<n; i++){
                if(i==0)
                    baslik[i]="1. SÜTUN";
                else{
                    sutSayisi = String.valueOf(i+1)+". SÜTUN";
                    baslik[i]=sutSayisi;
                }
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ m);
            for (int i = 0; i < m; i++) {
            satir= new String[n];
            for (int j = 0; j < n; j++) {
                  satir[j]= String.valueOf(matris[i][j]);
            }
            tmd.addRow(satir);
        }
         
         
         if(m>n){    // ASOL İŞLEMİNİ YAP
                  
            islemler islem= new islemler();
                 islemMatris1 = new float[n][m];
                 islemMatris1= islem.transpozeAl(matris, m, n);  //islemMatrisi1 transpoze
                 
                 islemMatris2= new float[n][n];
                 islemMatris2= islem.carmaIslemi(islemMatris1, n, m, matris, m, n); //islemMatrisi2 a çarpı atranspoze
                 
                 islemMatris3= new float[n][n];
                 islemMatris3= islem.tersAlma(islemMatris2, n, n); //islemMatrisi3 tersi alınmış hali
                 
                 islemMatris4 = new float[n][m];
                 islemMatris4 = islem.carmaIslemi(islemMatris3, n, n, islemMatris1, n, m);
                 
                 /*System.out.println("SÖZDE TERS");
                 System.out.println(m+" "+n);
                 for (int i = 0; i < n; i++) {
                     for (int j = 0; j < m; j++) {
                         System.out.print(islemMatris4[i][j]+" ");
                     }
                     System.out.println(" ");
                 }*/
                 
                jLabel9.setText("YAPILAN TOPLAM TOPLAMA SAYISI(TOPLAMA + CIKARMA):  "+(islem.toplamaSayac+islem.cikarmaSayac));
                jLabel10.setText("YAPILAN TOPLAM ÇARPMA SAYISI(ÇARPMA + BÖLME):  "+(islem.bolmeSayac+islem.carpmaSayac));
            }
            else{ //Aright=AT(AAT)−1    Atranspoze * ( A*Atranspoze)^-1
                 
                 islemler islem= new islemler();
                 islemMatris1 = new float[n][m];
                 islemMatris1= islem.transpozeAl(matris, m, n);  //islemMatrisi1 transpoze
                 
                 islemMatris2= new float[m][m];
                 islemMatris2= islem.carmaIslemi(matris, m, n, islemMatris1, n, m);
                 
                 islemMatris3= new float[m][m];
                 islemMatris3 = islem.tersAlma(islemMatris2, m, m);
                 
                 islemMatris4 = new float[n][m];
                 islemMatris4 = islem.carmaIslemi(islemMatris1,n , m, islemMatris3, m,m );
                 
                jLabel9.setText("YAPILAN TOPLAM TOPLAMA SAYISI(TOPLAMA + CIKARMA):  "+(islem.toplamaSayac+islem.cikarmaSayac));
                 jLabel10.setText("YAPILAN TOPLAM ÇARPMA SAYISI(ÇARPMA + BÖLME):  "+(islem.bolmeSayac+islem.carpmaSayac));
             }
            
            jLabel7.setText("ANA MATRİS YAZILMIŞTIR");
            
        /*
        DefaultTableModel tmd = new DefaultTableModel();
        jTable3.setModel(tmd);
        */
        

        anaPanel.setVisible(false);
        matrisIslemleri.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        kullanıcıMatrisi.setVisible(false);
        anaPanel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    int sayac=0;
   float [][]matris;
   int m,n;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        m= Integer.parseInt(jTextField1.getText());
        n= Integer.parseInt(jTextField2.getText());
        
        if(m<0 || n<0){
            System.out.println("");
            jLabel8.setText("LÜTFEN SATIR SÜTÜN SAYISINI NEGATİF GİRMEYİNİZ");
            jTextField1.setText("DEĞER GİRİNİZ");
            jTextField2.setText("DEĞER GİRİNİZ");
        }
        /*else if(m>5 || n>5){
            System.out.println("");
            jLabel8.setText("LÜTFEN SATIR SÜTÜN SAYISINI 5'DEN BÜYÜK GİRMEYİNİZ");
            jTextField1.setText("DEĞER GİRİNİZ");
            jTextField2.setText("DEĞER GİRİNİZ");
        }*/
        else if( m==n){
            jLabel8.setText("LÜTFEN SATIR VE SÜTUN SAYISINI AYNI GİRMEYİNİZ");
            jTextField1.setText("DEĞER GİRİNİZ");
            jTextField2.setText("DEĞER GİRİNİZ");
        }
        else{
        matris= new float[m][n];
        int deneme[][] = new int[2][34];
        jLabel6.setText("1. SATIR 1. SÜTUNU GİRİNİZ");
        kullanıcıMatrisi.setVisible(false);
        olusturulanMatris.setVisible(true); 
        
        for(int i=0; i<m; i++){
                for(int j=0; j<n; j++){
                    matris[i][j] = 1;
                }
                
            }
          //System.out.println(deneme.length);
            jTextField1.setText("DEĞER GİRİNİZ");
            jTextField2.setText("DEĞER GİRİNİZ");
        }
        
            jTextField1.setText("DEĞER GİRİNİZ");
            jTextField2.setText("DEĞER GİRİNİZ");
    }//GEN-LAST:event_jButton5ActionPerformed
    
    
    int a=0;
    int b=0;
    int sayac2=0;
    float [][]islemMatris1;
    float [][]islemMatris2;
    float [][]islemMatris3;
    float [][]islemMatris4;
    float [][]sonucMatris;
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            
        if(b == n-1){ 
            matris[a][b]=Float.parseFloat(jTextField4.getText());
            //System.out.println(a+" if 1 "+b+" değer "+matris[a][b]);
            a++;
            b=0;
            jTextField4.setText("DEĞER GİRİNİZ");
        }
        else{
            matris[a][b]=Float.parseFloat(jTextField4.getText());
            //System.out.println(a+" else "+b+" değer "+matris[a][b]);
            b++;
            jTextField4.setText("DEĞER GİRİNİZ");
        }
            jLabel6.setText((a+1)+". SATIR "+(b+1)+". SÜTUN GİRİNİZ");
        sayac++;
        if(sayac== (m*n)){
         olusturulanMatris.setVisible(false);
            matrisIslemleri.setVisible(true);
            //System.out.println("EN SON SAYACA GİRDİ");
            /*for(int i=0; i<m; i++){
                for(int j=0; j<n; j++){
                    System.out.print(matris[i][j]+" ");
                }
                System.out.println(" ");
            }*/
            
            String []baslik = new String[n];
            String sutSayisi;
            
            
            for(int i=0; i<n; i++){
                if(i==0)
                    baslik[i]="1. SÜTUN";
                else{
                    sutSayisi = String.valueOf(i+1)+". SÜTUN";
                    baslik[i]=sutSayisi;
                }
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ m);
            for (int i = 0; i < m; i++) {
            satir= new String[n];
            for (int j = 0; j < n; j++) {
                  satir[j]= String.valueOf(matris[i][j]);
            }
            tmd.addRow(satir);
        }
            // SÖZDE TERSİNİ ALMA İŞLEMİ BAŞLANGICI
             // M>N OLURSA A'SOL İŞLEMİ     Aleft=(ATA)−1AT     ( A* Atrasnpoze)^-1 * Atranspoze
             // M<N OLURSA A'SAĞ İŞLEMİ     Aright=AT(AAT)−1    Atranspoze * ( A*Atranspoze)^-1
             /*int sayac2=0;
    float [][]islemMatris1;
    float [][]islemMatris2;
    float [][]islemMatris3;
    float [][]islemMatris4;
    float [][]sonucMatris;*/
             
             if(m>n){    // ASOL İŞLEMİNİ YAP
                  
            islemler islem= new islemler();
                 islemMatris1 = new float[n][m];
                 islemMatris1= islem.transpozeAl(matris, m, n);  //islemMatrisi1 transpoze
                 
                 islemMatris2= new float[n][n];
                 islemMatris2= islem.carmaIslemi(islemMatris1, n, m, matris, m, n); //islemMatrisi2 a çarpı atranspoze
                 
                 islemMatris3= new float[n][n];
                 islemMatris3= islem.tersAlma(islemMatris2, n, n); //islemMatrisi3 tersi alınmış hali
                 
                 islemMatris4 = new float[n][m];
                 islemMatris4 = islem.carmaIslemi(islemMatris3, n, n, islemMatris1, n, m);
                 
                 /*System.out.println("SÖZDE TERS");
                 System.out.println(m+" "+n);
                 for (int i = 0; i < n; i++) {
                     for (int j = 0; j < m; j++) {
                         System.out.print(islemMatris4[i][j]+" ");
                     }
                     System.out.println(" ");
                 }*/
                 jLabel9.setText("YAPILAN TOPLAM TOPLAMA SAYISI(TOPLAMA + CIKARMA):  "+(islem.toplamaSayac+islem.cikarmaSayac));
                 jLabel10.setText("YAPILAN TOPLAM ÇARPMA SAYISI(ÇARPMA + BÖLME):  "+(islem.bolmeSayac+islem.carpmaSayac));
            }
             else{ //Aright=AT(AAT)−1    Atranspoze * ( A*Atranspoze)^-1
                 
                 islemler islem= new islemler();
                 islemMatris1 = new float[n][m];
                 islemMatris1= islem.transpozeAl(matris, m, n);  //islemMatrisi1 transpoze
                 
                 islemMatris2= new float[m][m];
                 islemMatris2= islem.carmaIslemi(matris, m, n, islemMatris1, n, m);
                 
                 islemMatris3= new float[m][m];
                 islemMatris3 = islem.tersAlma(islemMatris2, m, m);
                 
                 islemMatris4 = new float[n][m];
                 islemMatris4 = islem.carmaIslemi(islemMatris1,n , m, islemMatris3, m,m );
                 
                 jLabel9.setText("YAPILAN TOPLAM TOPLAMA SAYISI(TOPLAMA + CIKARMA):  "+(islem.toplamaSayac+islem.cikarmaSayac));
                 jLabel10.setText("YAPILAN TOPLAM ÇARPMA SAYISI(ÇARPMA + BÖLME):  "+(islem.bolmeSayac+islem.carpmaSayac));
             }
                 jLabel7.setText("ANA MATRİS YAZILMIŞTIR");
            jTextField4.setText("DEĞER GİRİNİZ");
        }
        
        jTextField4.setText("DEĞER GİRİNİZ");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 
        if(m>n){
        jLabel7.setText("At*A İŞLEMİ YAPILMIŞTIR");
        String []baslik = new String[n];
            String sutSayisi;
        
        for(int i=0; i<n; i++){
              sutSayisi = String.valueOf(i+1)+". SÜTUN";
              baslik[i]=sutSayisi;
                
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ n);
            for (int i = 0; i < n; i++) {
            satir= new String[n];
            for (int j = 0; j < n; j++) {
                  satir[j]= String.valueOf(islemMatris2[i][j]);
                }
                tmd.addRow(satir);
            }
        }
        else{
            jLabel7.setText("A*At İŞLEMİ YAPILMIŞTIR");
        String []baslik = new String[m];
            String sutSayisi;
        
        for(int i=0; i<m; i++){
              sutSayisi = String.valueOf(i+1)+". SÜTUN";
              baslik[i]=sutSayisi;
                
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ m);
            for (int i = 0; i < m; i++) {
            satir= new String[m];
            for (int j = 0; j < m; j++) {
                  satir[j]= String.valueOf(islemMatris2[i][j]);
                }
                tmd.addRow(satir);
            }
        }
            
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        matrisIslemleri.setVisible(false);
        anaPanel.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        
        jLabel7.setText("TERSİ ALINAN MATRİS TRANSPOZESİ İLE ÇARPILARAK ANA MATRİSİN SÖZDE TERSİ ALINMIŞTIR");
        String []baslik = new String[m];
            String sutSayisi;
        
        for(int i=0; i<m; i++){
              sutSayisi = String.valueOf(i+1)+". SÜTUN";
              baslik[i]=sutSayisi;
                
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ n);
            for (int i = 0; i < n; i++) {
            satir= new String[m];
            for (int j = 0; j < m; j++) {
                  satir[j]= String.valueOf(islemMatris4[i][j]);
            }
            tmd.addRow(satir);
        }
            islemler islem= new islemler();
            //jLabel9.setText("YAPILAN TOPLAM TOPLAMA SAYISI(TOPLAMA + CIKARMA):  "+(islem.toplamaSayac+islem.cikarmaSayac));
              //  jLabel10.setText("YAPILAN TOPLAM ÇARPMA SAYISI(ÇARPMA + BÖLME):  "+(islem.bolmeSayac+islem.carpmaSayac));
            
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        jLabel7.setText("BAŞTA GİRİLEN ANA MATRİS YAZILDI");
        
        String []baslik = new String[n];
            String sutSayisi;
            
            for(int i=0; i<n; i++){
                if(i==0)
                    baslik[i]="1. SÜTUN";
                else{
                    sutSayisi = String.valueOf(i+1)+". SÜTUN";
                    baslik[i]=sutSayisi;
                }
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ m);
            for (int i = 0; i < m; i++) {
            satir= new String[n];
            for (int j = 0; j < n; j++) {
                  satir[j]= String.valueOf(matris[i][j]);
            }
            tmd.addRow(satir);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            jLabel7.setText("MATRİSİN TRANSPOZESİ ALINDI");
            
        String []baslik = new String[m];
            String sutSayisi;
        
        for(int i=0; i<m; i++){
              sutSayisi = String.valueOf(i+1)+". SÜTUN";
              baslik[i]=sutSayisi;
                
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ n);
            for (int i = 0; i < n; i++) {
            satir= new String[m];
            for (int j = 0; j < m; j++) {
                  satir[j]= String.valueOf(islemMatris1[i][j]);
            }
            tmd.addRow(satir);
        }
            
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        if(m>n){
        jLabel7.setText("At*A SONUCUNUN TERSİ ALINMIŞTIR");
        String []baslik = new String[n];
            String sutSayisi;
        for(int i=0; i<n; i++){
              sutSayisi = String.valueOf(i+1)+". SÜTUN";
              baslik[i]=sutSayisi;
                
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ n);
            for (int i = 0; i < n; i++) {
            satir= new String[n];
            for (int j = 0; j < n; j++) {
                  satir[j]= String.valueOf(islemMatris3[i][j]);
                }
                tmd.addRow(satir);
            }
        } 
        else{
            jLabel7.setText("A*At SONUCUNUN TERSİ ALINMIŞTIR");
        String []baslik = new String[m];
            String sutSayisi;
        for(int i=0; i<m; i++){
              sutSayisi = String.valueOf(i+1)+". SÜTUN";
              baslik[i]=sutSayisi;
                
            }
            
            DefaultTableModel tmd = new DefaultTableModel(baslik,0);
            tablo.setModel(tmd);
            String satir[];
            tablo.setRowHeight(270/ m);
            for (int i = 0; i < m; i++) {
            satir= new String[m];
            for (int j = 0; j < m; j++) {
                  satir[j]= String.valueOf(islemMatris3[i][j]);
                }
                tmd.addRow(satir);
            }
            
            
        }
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel kullanıcıMatrisi;
    private javax.swing.JPanel matrisIslemleri;
    private javax.swing.JPanel olusturulanMatris;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}
